version: '3'

services:
  postgres:
    container_name: postgres1
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=PgDbFTW15
      - POSTGRES_DB=profiles
  redis:
    container_name: redis1
    image: "redis"
    ports:
      - "6379:6379"

  master:
    image: locustio/locust
    ports:
     - "8099:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
